### ISSUE TITLE
Implement auto complete to the "Input field" component

### ISSUE THREAD

**Issue by IanSeng** [eddieantonio/predictive-text-studio#132]
### Description 
- currently the input field does not support the functionally to display suggestions based on input text
- leverage on the pre-existing component `InputField.svelte` to improve the UI component

### Subtasks
- [x] input component with suggestion 
- [x] clickable and update the text in the input field 
- [x] component testing in cypress to ensure it work as expected
