### ISSUE TITLE
Enhance the efficiency by limiting the fetch amount 

### ISSUE THREAD

**Issue by IanSeng** [eddieantonio/predictive-text-studio#135]
# Description
Every time the worker starts up, it will fetch the entire language list. This is bad because it should really only be fetched maybe once a day, at most. But if you open a new tab, a new worker thread starts, which issues this request to the Keyman API 💀 - [@eddieantonio]

Is there a way you can set a limit to how often the data is fetched?

## Subtasks
- [x] Limit the number of time of fetching data 
- [x] If data is stored in the browser check last fetched date to determine if a new fetch is needed
- [x] Clear out the data before put to avoid redundancy of data
- [x] Unit testing 
- etc..
