### ISSUE TITLE
[META TASK]: Make the world's crappiest Predictive Text Studio

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/predictive-text-studio#46]
Allows the user to do the following:

 - [x] click on a `<input type="file">` field to upload their Excel file (will be solved by #43)
 - [x] type in their **exact** BCP-47 tag (#52)
 - [x] call the lexical model compiler (#53)
 - [x] click "download" -> this will just dump the compiled lexical model source code (#32) to a `<pre>` tag

**Comment by eddieantonio** [comment]
This _kind of_ exists right now. I'm gonna close it and mark it as invalid.
